# app/routes/_seed_data.py
# 280 questions total: 56 per sprint × 5 sprints (2 per day × 28 days)

INTERVIEW = [
    ("Tell me about yourself.", "Structure & Conciseness", 60, "Easy", 1),
    ("Walk me through your resume.", "Narrative & Relevance", 90, "Medium", 1),
    ("Why do you want to work here?", "Motivation & Fit", 60, "Easy", 2),
    ("Tell me about a time you faced a challenge at work.", "STAR Method", 90, "Medium", 2),
    ("What is your greatest strength?", "Self-Awareness", 45, "Easy", 3),
    ("What is your biggest weakness?", "Honesty & Growth", 60, "Hard", 3),
    ("Where do you see yourself in 5 years?", "Vision & Fit", 60, "Medium", 4),
    ("Why are you leaving your current role?", "Professional Narrative", 60, "Hard", 4),
    ("Describe a project you're most proud of.", "Impact & Ownership", 90, "Medium", 5),
    ("Tell me about a time you failed.", "Resilience & Learning", 90, "Hard", 5),
    ("How do you handle conflict with a colleague?", "Interpersonal Skills", 60, "Medium", 6),
    ("What motivates you day to day?", "Values & Drive", 60, "Easy", 6),
    ("Tell me about a time you led a team.", "Leadership", 90, "Medium", 7),
    ("How do you prioritize when everything is urgent?", "Time Management", 60, "Medium", 7),
    ("What's a skill you're currently developing?", "Growth Mindset", 45, "Easy", 8),
    ("Tell me about a time you disagreed with your manager.", "Diplomacy", 90, "Hard", 8),
    ("How do you approach a problem you've never seen before?", "Problem Solving", 60, "Medium", 9),
    ("What do you know about our company?", "Research & Interest", 60, "Easy", 9),
    ("Describe a time you had to influence without authority.", "Influence", 90, "Hard", 10),
    ("How do you handle feedback?", "Coachability", 45, "Easy", 10),
    ("Tell me about your biggest achievement.", "Impact", 90, "Medium", 11),
    ("What's a decision you regret?", "Reflection", 90, "Hard", 11),
    ("How do you stay current in your field?", "Continuous Learning", 60, "Easy", 12),
    ("Tell me about a time you had to say no.", "Boundaries & Prioritization", 60, "Medium", 12),
    ("Why should we hire you?", "Self-Advocacy", 60, "Medium", 13),
    ("What questions do you have for us?", "Curiosity & Engagement", 60, "Easy", 13),
    ("Describe your ideal work environment.", "Culture Fit", 60, "Medium", 14),
    ("Tell me about a time you went above and beyond.", "Initiative", 90, "Medium", 14),
    ("How do you handle pressure under tight deadlines?", "Composure", 60, "Medium", 15),
    ("Tell me about a time you had to learn something quickly.", "Learning Agility", 90, "Medium", 15),
    ("What's your biggest professional risk?", "Risk-Taking", 60, "Hard", 16),
    ("How do you measure success?", "Self-Assessment", 60, "Medium", 16),
    ("Tell me about a mentor who shaped you.", "Learning from Others", 90, "Easy", 17),
    ("How do you deal with ambiguity?", "Adaptability", 60, "Medium", 17),
    ("Describe a time you had to make a tough call.", "Judgment", 90, "Hard", 18),
    ("What's your communication style?", "Self-Awareness", 60, "Easy", 18),
    ("How do you handle rejection?", "Resilience", 60, "Medium", 19),
    ("Tell me about a time you changed your mind.", "Intellectual Humility", 90, "Medium", 19),
    ("What's a value you refuse to compromise on?", "Integrity", 60, "Hard", 20),
    ("How do you build relationships with stakeholders?", "Relationship Building", 90, "Medium", 20),
    ("Describe your ideal manager.", "Self-Awareness & Fit", 60, "Easy", 21),
    ("How do you handle multiple competing priorities?", "Prioritization", 60, "Medium", 21),
    ("Tell me about a time you had to influence a decision.", "Influence", 90, "Medium", 22),
    ("What's the most impactful feedback you've received?", "Coachability", 90, "Medium", 22),
    ("How would your colleagues describe you?", "Reputation", 60, "Easy", 23),
    ("Tell me about a time you had to adapt to change.", "Adaptability", 90, "Medium", 23),
    ("What's a project you'd like to work on next?", "Vision", 60, "Medium", 24),
    ("Describe a time you had to defend your position.", "Assertiveness", 90, "Hard", 24),
    ("How do you contribute to team culture?", "Collaboration", 60, "Easy", 25),
    ("Tell me about a time you made a mistake that impacted others.", "Accountability", 90, "Hard", 25),
    ("What's a challenge you're currently working through?", "Self-Awareness", 60, "Medium", 26),
    ("How do you approach negotiation?", "Negotiation", 60, "Medium", 26),
    ("Describe a time you had to say something difficult.", "Difficult Conversations", 90, "Hard", 27),
    ("What would your first 90 days look like in this role?", "Planning", 90, "Medium", 27),
    ("What do you want to learn in the next year?", "Growth Mindset", 60, "Easy", 28),
    ("Why are you the right fit for this role?", "Self-Advocacy", 60, "Medium", 28),
]

GD = [
    ("Is remote work here to stay?", "Opening Statement", 45, "Easy", 1),
    ("Should AI replace human decision-making?", "Balanced Argument", 60, "Medium", 1),
    ("Is hustle culture toxic?", "Perspective & Reasoning", 60, "Medium", 2),
    ("Does social media do more harm than good?", "Structured Argument", 60, "Easy", 2),
    ("Should college education be free?", "Pros & Cons", 60, "Medium", 3),
    ("Is WFH more productive than office?", "Evidence-Based Argument", 60, "Medium", 3),
    ("Should companies adopt 4-day work weeks?", "Nuanced Argument", 60, "Medium", 4),
    ("Is entrepreneurship better than a stable job?", "Personal Values", 60, "Medium", 4),
    ("Should CEOs be paid 100x their employees?", "Economic Reasoning", 60, "Hard", 5),
    ("Is privacy dead in the digital age?", "Ethical Reasoning", 60, "Hard", 5),
    ("Should India adopt a two-party system?", "Political Argument", 60, "Hard", 6),
    ("Is MBA still worth it in 2025?", "Cost-Benefit Analysis", 60, "Medium", 6),
    ("Should we ban targeted advertising?", "Ethics & Trade-offs", 60, "Medium", 7),
    ("Will AI create more jobs than it destroys?", "Long-term View", 60, "Hard", 7),
    ("Should companies pay for employee upskilling?", "Investment Argument", 60, "Medium", 8),
    ("Is competition always healthy?", "Nuanced View", 60, "Medium", 8),
    ("Is work-life balance a myth?", "Personal Values", 60, "Medium", 9),
    ("Should voting be mandatory?", "Civic Reasoning", 60, "Hard", 9),
    ("Is capitalism sustainable?", "Economic Critique", 60, "Hard", 10),
    ("Should education be skill-focused or knowledge-focused?", "Philosophy of Learning", 60, "Medium", 10),
    ("Is cancel culture a net positive or negative?", "Free Speech Debate", 60, "Hard", 11),
    ("Should governments regulate crypto?", "Regulatory Debate", 60, "Medium", 11),
    ("Is universal basic income a good idea?", "Economic Analysis", 60, "Hard", 12),
    ("Should companies be forced to be diverse?", "Policy Debate", 60, "Hard", 12),
    ("Is social media a public utility?", "Policy & Ethics", 60, "Medium", 13),
    ("Should healthcare be a right or privilege?", "Moral Reasoning", 60, "Hard", 13),
    ("Is it okay to lie to protect someone?", "Ethical Dilemma", 60, "Hard", 14),
    ("Should exams be abolished?", "Educational Reform", 60, "Medium", 14),
    ("Is AI-generated content real art?", "Definition Debate", 60, "Medium", 15),
    ("Should we colonize Mars?", "Long-term Vision", 60, "Medium", 15),
    ("Is religion still relevant in the 21st century?", "Philosophical Debate", 60, "Hard", 16),
    ("Should companies allow political discussions at work?", "Boundary Debate", 60, "Medium", 16),
    ("Is hard work enough to succeed today?", "Meritocracy Critique", 60, "Medium", 17),
    ("Should we have a maximum wage?", "Economic Policy", 60, "Hard", 17),
    ("Is data the new oil?", "Metaphor Analysis", 60, "Medium", 18),
    ("Should internships be paid?", "Labor Rights", 60, "Medium", 18),
    ("Is influencer culture harmful?", "Cultural Critique", 60, "Medium", 19),
    ("Should companies prioritize profit or purpose?", "Corporate Values", 60, "Hard", 19),
    ("Is lifelong marriage outdated?", "Social Norms", 60, "Hard", 20),
    ("Should sports be gender-segregated?", "Fairness Debate", 60, "Hard", 20),
    ("Is technology making us lonely?", "Psychological Impact", 60, "Medium", 21),
    ("Should we abolish the death penalty?", "Justice Debate", 60, "Hard", 21),
    ("Is the metaverse dead?", "Trend Analysis", 60, "Easy", 22),
    ("Should CEOs be on social media?", "Executive Presence", 60, "Easy", 22),
    ("Is failure necessary for success?", "Philosophical", 60, "Medium", 23),
    ("Should companies ban moonlighting?", "Employment Rights", 60, "Medium", 23),
    ("Is the 9-to-5 dead?", "Future of Work", 60, "Medium", 24),
    ("Should we worry about superintelligent AI?", "Existential Risk", 60, "Hard", 24),
    ("Is privacy more important than security?", "Trade-off Analysis", 60, "Hard", 25),
    ("Should employees have a right to disconnect?", "Labor Rights", 60, "Medium", 25),
    ("Is climate change the biggest threat we face?", "Priority Debate", 60, "Medium", 26),
    ("Should billionaires exist?", "Wealth Distribution", 60, "Hard", 26),
    ("Is traditional education obsolete?", "Education Reform", 60, "Medium", 27),
    ("Should we trust AI with our decisions?", "Trust & Technology", 60, "Hard", 27),
    ("Is optimism a strategy?", "Mindset Debate", 60, "Easy", 28),
    ("Should we have universal healthcare globally?", "Global Policy", 60, "Hard", 28),
]

LEADERSHIP = [
    ("How do you motivate an underperforming team member?", "Empathy & Action", 90, "Medium", 1),
    ("Describe a time you had to make a tough decision.", "Decision-Making", 90, "Medium", 1),
    ("How do you handle conflict between two team members?", "Mediation", 60, "Hard", 2),
    ("How do you give constructive feedback?", "Communication", 60, "Medium", 2),
    ("How do you build trust with a new team?", "Trust Building", 90, "Medium", 3),
    ("Describe your leadership style.", "Self-Awareness", 60, "Easy", 3),
    ("How do you handle consistent underperformance?", "Accountability", 90, "Hard", 4),
    ("How do you align a team around a vision?", "Vision Communication", 90, "Medium", 4),
    ("Tell me about a time you had to let someone go.", "Difficult Conversations", 90, "Hard", 5),
    ("How do you prioritize what your team works on?", "Strategic Prioritization", 60, "Medium", 5),
    ("How do you handle disagreement with your boss?", "Managing Up", 60, "Medium", 6),
    ("How do you develop your team members?", "Coaching & Growth", 60, "Medium", 6),
    ("How do you handle change resistance?", "Change Management", 90, "Hard", 7),
    ("What's the hardest leadership decision you've made?", "Judgment", 90, "Hard", 7),
    ("How do you set goals for your team?", "Goal Setting", 60, "Medium", 8),
    ("How do you handle an employee who challenges you publicly?", "Composure", 90, "Hard", 8),
    ("Describe a time you had to lead through a crisis.", "Crisis Leadership", 90, "Hard", 9),
    ("How do you balance empathy with accountability?", "Balance", 60, "Hard", 9),
    ("How do you recognize good work?", "Recognition", 60, "Easy", 10),
    ("What do you do when your team disagrees with you?", "Openness", 60, "Medium", 10),
    ("How do you onboard a new team member?", "Onboarding", 60, "Easy", 11),
    ("How do you handle an employee's personal crisis?", "Empathy", 90, "Hard", 11),
    ("How do you give feedback to a peer?", "Peer Feedback", 60, "Medium", 12),
    ("How do you handle a star performer who's toxic?", "Values vs Performance", 90, "Hard", 12),
    ("How do you set boundaries with your team?", "Boundaries", 60, "Medium", 13),
    ("How do you handle a mistake your team made?", "Ownership", 60, "Medium", 13),
    ("How do you manage your own time as a leader?", "Self-Management", 60, "Medium", 14),
    ("How do you decide when to delegate vs do it yourself?", "Delegation", 60, "Medium", 14),
    ("Describe a time you had to defend your team.", "Advocacy", 90, "Medium", 15),
    ("How do you build a culture of psychological safety?", "Culture Building", 90, "Hard", 15),
    ("How do you handle layoffs?", "Tough Decisions", 90, "Hard", 16),
    ("How do you build trust with a skeptical stakeholder?", "Stakeholder Management", 90, "Medium", 16),
    ("How do you handle a team member who wants your job?", "Ambition Management", 60, "Hard", 17),
    ("How do you keep your team motivated during slow periods?", "Motivation", 60, "Medium", 17),
    ("How do you handle an employee who lies?", "Integrity", 90, "Hard", 18),
    ("How do you make decisions with incomplete information?", "Decision-Making", 90, "Hard", 18),
    ("How do you handle a merger or acquisition?", "Change Leadership", 90, "Hard", 19),
    ("How do you hire well?", "Hiring", 60, "Medium", 19),
    ("How do you handle a high-potential employee who's bored?", "Development", 60, "Medium", 20),
    ("Describe your biggest leadership failure.", "Vulnerability", 90, "Hard", 20),
    ("How do you give bad news to your team?", "Communication", 90, "Hard", 21),
    ("How do you handle cross-functional conflict?", "Diplomacy", 90, "Medium", 21),
    ("How do you know when to escalate?", "Judgment", 60, "Medium", 22),
    ("How do you run an effective 1:1?", "Coaching", 60, "Easy", 22),
    ("How do you handle a team member who's burned out?", "Wellbeing", 90, "Hard", 23),
    ("How do you lead when you don't have authority?", "Influence", 90, "Hard", 23),
    ("How do you build a successor?", "Succession", 60, "Medium", 24),
    ("How do you handle disagreements among your direct reports?", "Mediation", 90, "Medium", 24),
    ("How do you handle a project that's failing?", "Course Correction", 90, "Hard", 25),
    ("How do you celebrate team wins?", "Culture", 60, "Easy", 25),
    ("How do you protect your team from bad decisions above you?", "Shielding", 90, "Hard", 26),
    ("How do you manage a remote team?", "Remote Leadership", 90, "Medium", 26),
    ("How do you build trust across cultures?", "Cultural Intelligence", 90, "Medium", 27),
    ("What's your leadership philosophy?", "Self-Awareness", 60, "Easy", 27),
    ("How do you want your team to remember you?", "Legacy", 60, "Medium", 28),
    ("What's the most important lesson you've learned as a leader?", "Reflection", 90, "Medium", 28),
]

STORYTELLING = [
    ("Tell me about a defining moment in your career.", "Narrative Arc", 90, "Medium", 1),
    ("Describe a failure that shaped you.", "Vulnerability & Insight", 90, "Hard", 1),
    ("What is the story behind your biggest achievement?", "Emotional Hooks", 90, "Medium", 2),
    ("Tell me about a person who changed your life.", "Character & Impact", 90, "Medium", 2),
    ("Describe a moment you felt truly alive.", "Sensory Detail", 90, "Medium", 3),
    ("What's a lesson you learned the hard way?", "Reflection", 90, "Medium", 3),
    ("Tell me about a time you surprised yourself.", "Self-Discovery", 90, "Medium", 4),
    ("Describe a place that shaped who you are.", "Setting & Meaning", 90, "Easy", 4),
    ("What's a belief you've changed your mind about?", "Intellectual Honesty", 90, "Hard", 5),
    ("Tell me about a risk that paid off.", "Courage & Outcome", 90, "Medium", 5),
    ("Describe a moment of unexpected kindness.", "Emotion & Empathy", 90, "Easy", 6),
    ("Tell me about a time you felt like an outsider.", "Belonging", 90, "Hard", 6),
    ("What's a story you tell about yourself often?", "Identity", 90, "Medium", 7),
    ("Tell me about a loss that changed you.", "Grief & Growth", 90, "Hard", 7),
    ("Describe a moment when you knew you were right.", "Conviction", 90, "Medium", 8),
    ("Tell me about a time you had to start over.", "Resilience", 90, "Medium", 8),
    ("What's the most embarrassing thing that's happened to you?", "Vulnerability", 90, "Medium", 9),
    ("Describe a person who believed in you before you did.", "Support", 90, "Easy", 9),
    ("Tell me about a time you broke a rule.", "Rebellion", 90, "Medium", 10),
    ("What's a story you wish you could rewrite?", "Regret & Reflection", 90, "Hard", 10),
    ("Describe the happiest moment of your life.", "Joy", 90, "Easy", 11),
    ("Tell me about a moment when you had to choose between two paths.", "Dilemma", 90, "Medium", 11),
    ("What's the most important thing you've learned about yourself?", "Self-Discovery", 90, "Medium", 12),
    ("Describe a time you were rejected and it changed you.", "Rejection", 90, "Hard", 12),
    ("Tell me about a time you were the underdog.", "Underdog", 90, "Medium", 13),
    ("What's a story that always makes you cry?", "Emotional Trigger", 90, "Hard", 13),
    ("Describe a time you stood up for something you believed in.", "Values", 90, "Medium", 14),
    ("Tell me about a time when you were truly scared.", "Fear & Courage", 90, "Hard", 14),
    ("What's a moment when you felt completely present?", "Mindfulness", 90, "Medium", 15),
    ("Describe a time when you had to let go of something you loved.", "Loss", 90, "Hard", 15),
    ("Tell me about a time you were underestimated.", "Underestimation", 90, "Medium", 16),
    ("What's a story you've never told anyone?", "Vulnerability", 90, "Hard", 16),
    ("Describe a moment when you felt deeply understood.", "Connection", 90, "Easy", 17),
    ("Tell me about a time you were the villain in someone's story.", "Self-Awareness", 90, "Hard", 17),
    ("What's a story that shaped your sense of humor?", "Identity", 90, "Medium", 18),
    ("Describe a moment when time slowed down.", "Presence", 90, "Medium", 18),
    ("Tell me about a time when you forgave someone.", "Forgiveness", 90, "Hard", 19),
    ("What's a moment you wish you could live again?", "Nostalgia", 90, "Medium", 19),
    ("Describe a time when you felt truly brave.", "Courage", 90, "Medium", 20),
    ("Tell me about a moment of profound silence.", "Stillness", 90, "Hard", 20),
    ("What's a moment that felt like an ending and a beginning?", "Transitions", 90, "Medium", 21),
    ("Describe a time when you had to fight for something.", "Perseverance", 90, "Medium", 21),
    ("Tell me about a moment that changed how you see the world.", "Paradigm Shift", 90, "Hard", 22),
    ("What's a story that reveals something about your family?", "Heritage", 90, "Medium", 22),
    ("Describe a moment of profound gratitude.", "Gratitude", 90, "Easy", 23),
    ("Tell me about a time when you had to say goodbye.", "Farewell", 90, "Hard", 23),
    ("What's a moment when you felt like you belonged?", "Belonging", 90, "Medium", 24),
    ("Describe a time when you surprised yourself with your strength.", "Strength", 90, "Medium", 24),
    ("Tell me about a moment when you realized you'd grown up.", "Coming of Age", 90, "Hard", 25),
    ("What's a story that always makes you laugh?", "Joy", 90, "Easy", 25),
    ("Describe a moment of unexpected beauty.", "Awe", 90, "Medium", 26),
    ("Tell me about a time when you had to trust your gut.", "Intuition", 90, "Medium", 26),
    ("What's a moment when you realized you were wrong?", "Humility", 90, "Hard", 27),
    ("Describe a time when you felt truly seen.", "Recognition", 90, "Medium", 27),
    ("What's a story you'd want to be remembered by?", "Legacy", 90, "Medium", 28),
    ("Tell me about a moment when everything clicked.", "Clarity", 90, "Medium", 28),
]

CHARISMA = [
    ("How would you introduce yourself in 30 seconds at a networking event?", "Presence", 30, "Easy", 1),
    ("How do you make someone feel heard in a conversation?", "Connection", 60, "Medium", 1),
    ("How do you command a room without dominating it?", "Executive Presence", 60, "Hard", 2),
    ("What makes someone instantly likable?", "Social Intelligence", 60, "Medium", 2),
    ("How do you handle an awkward silence?", "Composure", 30, "Easy", 3),
    ("How do you remember names and details about people?", "Attention", 45, "Medium", 3),
    ("How do you end a conversation gracefully?", "Social Grace", 30, "Easy", 4),
    ("How do you disagree without being disagreeable?", "Tact", 60, "Hard", 4),
    ("How do you show confidence without arrogance?", "Humility & Presence", 60, "Hard", 5),
    ("How do you give a compliment that lands?", "Sincerity", 30, "Easy", 5),
    ("How do you handle someone who talks over you?", "Assertiveness", 60, "Medium", 6),
    ("How do you build rapport in 5 minutes?", "Speed & Warmth", 60, "Medium", 6),
    ("How do you read a room?", "Situational Awareness", 60, "Hard", 7),
    ("What's your signature move in social settings?", "Authentic Presence", 60, "Medium", 7),
    ("How do you handle someone who's rude to you?", "Grace Under Pressure", 60, "Hard", 8),
    ("How do you make a first impression that lasts?", "First Impressions", 60, "Medium", 8),
    ("How do you keep a conversation going?", "Curiosity", 45, "Easy", 9),
    ("How do you handle being interrupted?", "Assertiveness", 45, "Medium", 9),
    ("How do you show you care without being overbearing?", "Empathy", 60, "Medium", 10),
    ("How do you tell a story that captivates?", "Narrative", 60, "Hard", 10),
    ("How do you handle criticism in public?", "Composure", 60, "Hard", 11),
    ("How do you make people feel important?", "Recognition", 45, "Easy", 11),
    ("How do you handle small talk when you hate it?", "Adaptability", 45, "Medium", 12),
    ("How do you project warmth and authority at once?", "Executive Presence", 60, "Hard", 12),
    ("How do you handle a difficult client?", "Composure", 90, "Hard", 13),
    ("How do you recover from a social faux pas?", "Grace", 60, "Medium", 13),
    ("How do you use silence to your advantage?", "Power of Pause", 60, "Medium", 14),
    ("How do you know when to speak and when to listen?", "Timing", 60, "Medium", 14),
    ("How do you show vulnerability without losing authority?", "Balance", 60, "Hard", 15),
    ("How do you enter a room with presence?", "Entrance", 45, "Medium", 15),
    ("How do you handle someone who's dismissive of you?", "Poise", 60, "Hard", 16),
    ("How do you make a memorable exit?", "Closure", 45, "Easy", 16),
    ("How do you handle someone who's flirting with you at work?", "Boundaries", 60, "Hard", 17),
    ("How do you give feedback in a way that's received well?", "Tact", 60, "Medium", 17),
    ("How do you show up in a meeting where you're the most junior?", "Presence", 60, "Medium", 18),
    ("How do you handle someone who cries in a meeting?", "Compassion", 60, "Hard", 18),
    ("How do you tell someone no with grace?", "Boundaries", 45, "Medium", 19),
    ("How do you use humor effectively in professional settings?", "Timing", 60, "Medium", 19),
    ("How do you build a personal brand that feels authentic?", "Authenticity", 60, "Medium", 20),
    ("How do you handle a room where nobody knows you?", "Entering Cold", 60, "Medium", 20),
    ("How do you make someone feel like the only person in the room?", "Presence", 60, "Hard", 21),
    ("How do you handle a conversation that goes badly?", "Recovery", 60, "Medium", 21),
    ("How do you stay calm when you're being attacked?", "Composure", 60, "Hard", 22),
    ("How do you show interest without seeming fake?", "Sincerity", 45, "Medium", 22),
    ("How do you handle a colleague who spreads rumors about you?", "Dignity", 90, "Hard", 23),
    ("How do you inspire people with your words?", "Inspiration", 60, "Hard", 23),
    ("How do you connect with someone you have nothing in common with?", "Bridge Building", 60, "Medium", 24),
    ("How do you make an apology that actually works?", "Accountability", 60, "Hard", 24),
    ("How do you handle attention you don't want?", "Boundaries", 60, "Medium", 25),
    ("How do you make your presence felt in a virtual meeting?", "Digital Charisma", 45, "Medium", 25),
    ("How do you handle someone who's clearly upset with you?", "Repair", 60, "Hard", 26),
    ("How do you bring out the best in others?", "Elevation", 60, "Medium", 26),
    ("How do you handle being the center of attention?", "Comfort with Spotlight", 45, "Medium", 27),
    ("How do you create a moment that people remember?", "Memorability", 60, "Medium", 27),
    ("How do you show up as your most authentic self at work?", "Authenticity", 60, "Medium", 28),
    ("How do you want people to feel after meeting you?", "Impact", 60, "Medium", 28),
]


def _build_seed_list():
    out = []
    for item in INTERVIEW:
        out.append(("interview",) + item)
    for item in GD:
        out.append(("gd",) + item)
    for item in LEADERSHIP:
        out.append(("leadership",) + item)
    for item in STORYTELLING:
        out.append(("storytelling",) + item)
    for item in CHARISMA:
        out.append(("charisma",) + item)
    return out


SEED_QUESTIONS = _build_seed_list()
